/**
 * agent-hub — the public library surface of the rewrite.
 *
 * Provider-neutral by contract: one hub object (`AgentHub`) composing the
 * Git-free interaction core (`InteractionKernel`, P1) and the canonical
 * durable custody core (`WorkspaceLifecycle`, P2 — AGENT_HUB_HOME-anchored
 * worktrees, exact results, handoff, retention, conditional GC).
 * Interaction crosses ONLY the shipped provider transports, auto-selected
 * per provider:
 *
 *   - omp    → omp-rpc          (RPC v2 dialect only; no v1 fallback)
 *   - pi     → pi-rpc
 *   - agy    → agy-stream-json
 *   - hermes → hermes-acp
 *
 * There is deliberately no delegate / fanout / session / live / competition
 * / judge / auto-merge vocabulary here, no transport-pinning on public
 * requests, and no compatibility aliases for any of it.
 */

export { AgentHubError } from "./errors.js";

export {
  CHATGPT_PAIR_PROVIDERS,
  CHATGPT_PAIR_SCHEMA,
  assertChatGptPairRepository,
  chatGptDoctor,
  inspectChatGptPair,
  isChatGptPairProvider,
  pairRepository,
  readChatGptPair,
  resolveChatGptStateHome,
  resolvePairedWorkspace,
  unpairRepository,
  type ChatGptPair,
  type ChatGptPairProvider,
  type ChatGptPairStatus,
} from "./chatgpt/index.js";

export {
  AgentHub,
  AgentHubSupervisor,
  processHubSupervisor,
  WorkspaceLifecycle,
  HUB_PROVIDERS,
  HUB_PROCESS_SESSION_QUOTA,
  HUB_GC_SWEEP_INTERVAL_MS,
  bridgeTransportFactory,
  productionBridgedFactories,
  productionBridgedProviderFactories,
  AttachInputPump,
  ATTACH_QUEUE_MAX_COMMANDS,
  ATTACH_QUEUE_MAX_BYTES,
  ATTACH_LINE_MAX_BYTES,
  ATTACH_CHUNK_MAX_BYTES,
  type AgentHubOptions,
  type AttachInputEvent,
  type BridgedTransportFactory,
  type CloseInput,
  type CustodyStatus,
  type FinalizeReport,
  type GcReport,
  type GcRetainCode,
  type HandoffDecision,
  type HandoffDecisionInput,
  type HandoffInput,
  type HubCleanupDocument,
  type HubCloseDocument,
  type HubOpen,
  type HubStartDocument,
  type HubWaitDocument,
  type HubStatusDocument,
  type PublishedTurn,
  type RecoveryReport,
  type ResumeOptions,
  type StartOptions,
  type TurnDocument,
  type WorkspaceHandoff,
  type WorkspaceInspection,
  type WorkspaceLifecycleOptions,
  type WorkspaceRecord,
  type WorkspaceResultRecord,
} from "./hub/index.js";

// The interaction core stays directly constructible for embedders that bring
// their own durable/lifecycle layer; its seams (DurableMirror,
// onProviderSpawn, attached) are the supported extension points.
export {
  InteractionKernel,
  DEFAULT_MAX_TEXT_BYTES,
  DEFAULT_SESSION_QUOTA,
  FOLLOW_UP_MAX_MESSAGE_BYTES,
  FOLLOW_UP_QUEUE_MAX_BYTES,
  FOLLOW_UP_QUEUE_MAX_MESSAGES,
  SESSION_SCHEMA_VERSION,
  asKernelError,
  isCommandKind,
  isPermissionDecision,
  isTerminalStatus,
  kernelError,
  parseResumeState,
  parseSessionRecord,
  validateCapabilities,
  CAPABILITY_NAMES,
  COMMAND_KINDS,
  OBSERVATION_NAMES,
  SESSION_STATUSES,
  TERMINAL_STATUSES,
  boundEvent,
  eventBytes,
  EventRing,
  EventSubscription,
  truncateUtf8,
  EVENT_MAX_BYTES,
  RING_MAX_BYTES,
  RING_MAX_EVENTS,
  type BoundedText,
  type CancelCommand,
  type Capabilities,
  type CapabilityClaim,
  type CapabilityName,
  type CapabilitySupport,
  type CloseResult,
  type Command,
  type CommandAccepted,
  type CommandKind,
  type CommandOutcome,
  type DurableMirror,
  type ErrorStage,
  type EventBody,
  type EventKind,
  type FollowUpCommand,
  type KernelError,
  type KernelOptions,
  type KernelPhase,
  type LaunchReport,
  type LaunchRequest,
  type ObservationName,
  type PermissionDecision,
  type PermissionPolicy,
  type PermissionResponseCommand,
  type ProcessFacts,
  type ProbeResult,
  type PromptCommand,
  type ProviderFactory,
  type ProviderId,
  type ProbeDocument,
  type ResumeState,
  type ResumeVerification,
  type SessionEvent,
  type SessionId,
  type SessionRecord,
  type SessionStatus,
  type StartRequest,
  type StartResult,
  type StatusCommand,
  type SteerCommand,
  type StopMode,
  type StopReport,
  type Transport,
  type TransportDescriptor,
  type TransportFactory,
  type TransportId,
  type TransportSelection,
  type TurnResult,
  type Usage,
} from "./kernel/index.js";
